package com.foodadviser.model;
// Generated Jun 10, 2014 8:13:33 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name="comment"
    ,catalog="test"
)
public class Comment  implements java.io.Serializable {


     private Long commentId;
     private Review review;
     private long customerId;
     private String commentDetail;
     private byte[] picture;

    public Comment() {
    }

	
    public Comment(long customerId) {
        this.customerId = customerId;
    }
    public Comment(Review review, long customerId, String commentDetail, byte[] picture) {
       this.review = review;
       this.customerId = customerId;
       this.commentDetail = commentDetail;
       this.picture = picture;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="COMMENT_ID", unique=true, nullable=false)
    public Long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REVIEW_Id")
    public Review getReview() {
        return this.review;
    }
    
    public void setReview(Review review) {
        this.review = review;
    }
    
    @Column(name="CUSTOMER_Id", nullable=false)
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }
    
    @Column(name="COMMENT_DETAIL", length=45)
    public String getCommentDetail() {
        return this.commentDetail;
    }
    
    public void setCommentDetail(String commentDetail) {
        this.commentDetail = commentDetail;
    }
    
    @Column(name="picture")
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }




}


