package com.foodadviser.model;
// Generated Jun 10, 2014 8:13:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="customer"
    ,catalog="test"
)
public class Customer  implements java.io.Serializable {


     private Long customerId;
     private String name;
     private String address;
     private Date createdDate;
     private String emailId;
     private String password;
     private byte[] image;
     private Set<Review> reviews = new HashSet<Review>(0);
//     private Set<Review> reviews_1 = new HashSet<Review>(0);

    public Customer() {
    }

	
    public Customer(String name, String address, Date createdDate, String emailId, String password) {
        this.name = name;
        this.address = address;
        this.createdDate = createdDate;
        this.emailId = emailId;
        this.password = password;
    }
//    public Customer(String name, String address, Date createdDate, String emailId, String password, byte[] image, Set<Review> reviews, Set<Review> reviews_1) {
//       this.name = name;
//       this.address = address;
//       this.createdDate = createdDate;
//       this.emailId = emailId;
//       this.password = password;
//       this.image = image;
//       this.reviews = reviews;
//       this.reviews_1 = reviews_1;
//    }
//   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="CUSTOMER_ID", unique=true, nullable=false)
    public Long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
    
    @Column(name="NAME", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="ADDRESS", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="EMAIL_ID", nullable=false, length=45)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    
    @Column(name="PASSWORD", nullable=false, length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="IMAGE")
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="customer")
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
//@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="customer")
//    public Set<Review> getReviews_1() {
//        return this.reviews_1;
//    }
//    
//    public void setReviews_1(Set<Review> reviews_1) {
//        this.reviews_1 = reviews_1;
//    }




}


