package com.foodadviser.model;
// Generated Jun 16, 2014 7:52:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
    ,catalog="test"
)
public class Event  implements java.io.Serializable {


     private Long eventId;
     private String eventName;
     private String eventDetail;
     private String eventType;
     private String eventPlace;
     private Date startingTime;
     private Date endingTime;
     private Date startingDate;
     private Date endingDate;
     private String image;

    public Event() {
    }

	
    public Event(String eventName, String eventDetail, String eventType, String eventPlace) {
        this.eventName = eventName;
        this.eventDetail = eventDetail;
        this.eventType = eventType;
        this.eventPlace = eventPlace;
    }
    public Event(String eventName, String eventDetail, String eventType, String eventPlace, Date startingTime, Date endingTime, Date startingDate, Date endingDate, String image) {
       this.eventName = eventName;
       this.eventDetail = eventDetail;
       this.eventType = eventType;
       this.eventPlace = eventPlace;
       this.startingTime = startingTime;
       this.endingTime = endingTime;
       this.startingDate = startingDate;
       this.endingDate = endingDate;
       this.image = image;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="EVENT_ID", unique=true, nullable=false)
    public Long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }
    
    @Column(name="EVENT_NAME", nullable=false, length=45)
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    
    @Column(name="EVENT_DETAIL", nullable=false, length=45)
    public String getEventDetail() {
        return this.eventDetail;
    }
    
    public void setEventDetail(String eventDetail) {
        this.eventDetail = eventDetail;
    }
    
    @Column(name="EVENT_TYPE", nullable=false, length=45)
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
    
    @Column(name="EVENT_PLACE", nullable=false, length=45)
    public String getEventPlace() {
        return this.eventPlace;
    }
    
    public void setEventPlace(String eventPlace) {
        this.eventPlace = eventPlace;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="STARTING_TIME", length=8)
    public Date getStartingTime() {
        return this.startingTime;
    }
    
    public void setStartingTime(Date startingTime) {
        this.startingTime = startingTime;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="ENDING_TIME", length=8)
    public Date getEndingTime() {
        return this.endingTime;
    }
    
    public void setEndingTime(Date endingTime) {
        this.endingTime = endingTime;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="STARTING_DATE", length=10)
    public Date getStartingDate() {
        return this.startingDate;
    }
    
    public void setStartingDate(Date startingDate) {
        this.startingDate = startingDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ENDING_DATE", length=10)
    public Date getEndingDate() {
        return this.endingDate;
    }
    
    public void setEndingDate(Date endingDate) {
        this.endingDate = endingDate;
    }
    
    @Column(name="image", length=45)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

@Override
    public int hashCode() {
        int hash = 0;
        hash += (eventId != null ? eventId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Event)) {
            return false;
        }
        Event other = (Event) object;
        if ((this.eventId == null && other.eventId != null) || (this.eventId != null && !this.eventId.equals(other.eventId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.foodadviser.model.Event[ eventId=" + eventId + " ]";
    }


}


