package com.foodadviser.model;
// Generated Jun 10, 2014 8:13:33 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Restaurantdetail generated by hbm2java
 */
@Entity
@Table(name="restaurantdetail"
    ,catalog="test"
)
public class Restaurantdetail  implements java.io.Serializable {


     private int id;
     private String name;
     private String type;
     private String image;
     private Set<Review> reviews = new HashSet<Review>(0);

    public Restaurantdetail() {
    }

	
    public Restaurantdetail(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Restaurantdetail(int id, String name, String type, String image, Set<Review> reviews) {
       this.id = id;
       this.name = name;
       this.type = type;
       this.image = image;
       this.reviews = reviews;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="image", length=45)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="restaurantdetail")
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }




}


