package com.foodadviser.model;
// Generated Jun 10, 2014 8:13:33 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name="review"
    ,catalog="test"
)
public class Review  implements java.io.Serializable {


     private Integer reviewId;
     private Restaurantdetail restId;
     private Customer customerId;
     private String reviewDetails;
     private String picture;
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Review() {
    }

	
//    public Review(Restaurantdetail restaurantdetail, Customer customer, String reviewDetails) {
//        this.restaurantdetail = restaurantdetail;
//        this.customer = customer;
//        this.reviewDetails = reviewDetails;
//    }
    
    public Review(Integer reviewId, Restaurantdetail restId, Customer customerId, String reviewDetails, String picture) {
       this.reviewId = reviewId;
        this.restId = restId;
        this.customerId = customerId;
        this.reviewDetails = reviewDetails;
        this.picture = picture;
    }
    
//    public Review(Restaurantdetail restaurantdetail, Customer customer, String reviewDetails, String picture, Set<Comment> comments) {
//       this.restaurantdetail = restaurantdetail;
//       this.customer = customer;
//       this.reviewDetails = reviewDetails;
//       this.picture = picture;
//       this.comments = comments;
//    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="REVIEW_ID", unique=true, nullable=false)
    public Integer getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REST_Id", nullable=false)
    public Restaurantdetail getRestaurantdetail() {
        return this.restId;
    }
    
    public void setRestaurantdetail(Restaurantdetail restaurantdetail) {
        this.restId = restaurantdetail;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOMER_Id", nullable=false)
    public Customer getCustomer() {
        return this.customerId;
    }
    
    public void setCustomer(Customer customer) {
        this.customerId = customer;
    }
    
    @Column(name="REVIEW_DETAILS", nullable=false, length=45)
    public String getReviewDetails() {
        return this.reviewDetails;
    }
    
    public void setReviewDetails(String reviewDetails) {
        this.reviewDetails = reviewDetails;
    }
    
    @Column(name="picture", length=45)
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="review")
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


